#include $(OBJ_DIR)/src/ap/ap.mk
include $(LVGL_DIR)/ui/wpa/common/common.mk
#include $(OBJ_DIR)/src/crypto/crypto.mk
#include $(OBJ_DIR)/src/drivers/driver.mk
#include $(OBJ_DIR)/src/eap_common/eap_common.mk
#include $(OBJ_DIR)/src/eap_peer/eap_peer.mk
#include $(OBJ_DIR)/src/eap_server/eap_server.mk
#include $(OBJ_DIR)/src/eapol_auth/eapol_auth.mk
#include $(OBJ_DIR)/src/eapol_supp/eapol_supp.mk
#include $(OBJ_DIR)/src/fst/fst.mk
#include $(OBJ_DIR)/src/l2_packet/l2_packet.mk
#include $(OBJ_DIR)/src/p2p/p2p.mk
#include $(OBJ_DIR)/src/pae/pae.mk
#include $(OBJ_DIR)/src/radius/radius.mk
#include $(OBJ_DIR)/src/rsn_supp/rsn_supp.mk
#include $(OBJ_DIR)/src/tls/tls.mk
include $(LVGL_DIR)/ui/wpa/utils/utils.mk
#include $(OBJ_DIR)/src/wps/wps.mk